apiVersion: v1
kind: ConfigMap
metadata:
  name: test-config
data:
  backend-url: {{ include "url-manager.backendServiceUrl" . }}
  database-host: {{ include "url-manager.databaseHost" . }}
  redis-address: {{ include "url-manager.redisAddress" . }}
