apiVersion: v1
kind: Service
metadata:
  name: {{ include "url-manager.fullname" . }}-backend
  labels:
    {{- include "url-manager.backend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "url-manager.backend.selectorLabels" . | nindent 4 }}