run:
  timeout: 5m
  modules-download-mode: readonly
  go: "1.21"

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters:
  enable:
    - asciicheck
    - bodyclose
    - cyclop
    - dupl
    - durationcheck
    - errorlint
    - exhaustive
    - exportloopref
    - forbidigo
    - funlen
    - gci
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomnd
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nlreturn
    - noctx
    - nolintlint
    - paralleltest
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - stylecheck
    - tagliatelle
    - tenv
    - testpackage
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - wastedassign
    - whitespace
    - wrapcheck

linters-settings:
  cyclop:
    max-complexity: 15
    package-average: 10.0
    skip-tests: true

  dupl:
    threshold: 100

  funlen:
    lines: 80
    statements: 40

  gci:
    sections:
      - standard
      - default
      - prefix(url-manager-system/backend)

  gocognit:
    min-complexity: 15

  goconst:
    min-len: 2
    min-occurrences: 3

  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style

  gocyclo:
    min-complexity: 15

  godot:
    scope: declarations
    capital: true

  gomnd:
    ignored-numbers:
      - '0666'
      - '0755'
      - '24'
      - '60'
      - '1000'
      - '1024'

  gosec:
    excludes:
      - G404 # 随机数生成器

  lll:
    line-length: 120

  misspell:
    locale: US

  nakedret:
    max-func-lines: 30

  nestif:
    min-complexity: 4

  nlreturn:
    block-size: 5

  nolintlint:
    allow-leading-space: true
    allow-unused: false
    require-explanation: false
    require-specific: false

  revive:
    rules:
      - name: exported
        arguments:
          - checkPrivateReceivers
          - sayRepetitiveInsteadOfStutters

  stylecheck:
    checks: ["all", "-ST1000", "-ST1003", "-ST1016", "-ST1020", "-ST1021", "-ST1022"]

  tagliatelle:
    case:
      rules:
        json: snake

  testpackage:
    skip-regexp: (export|internal)_test\.go

  unused:
    check-exported: false

  wrapcheck:
    ignoreSigs:
      - .Errorf(
      - errors.New(
      - errors.Unwrap(
      - .Wrap(
      - .Wrapf(

issues:
  exclude-rules:
    # 忽略测试文件中的某些检查
    - path: _test\.go
      linters:
        - cyclop
        - dupl
        - funlen
        - gocognit
        - gocyclo
        - gomnd
        - lll

    # 忽略生成的文件
    - path: \.pb\.go
      linters:
        - all

    # 忽略main函数中的退出调用
    - path: cmd/
      text: "os.Exit"
      linters:
        - gocritic

  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0