apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${DEPLOYMENT_NAME}
  labels:
    app: ephemeral-url
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ephemeral-url
  template:
    metadata:
      labels:
        app: ephemeral-url
    spec:
      containers:
      - name: app
        image: nginx:1.20
        ports:
        - containerPort: 80
          protocol: TCP
        env:
        - name: PROJECT_NAME
          value: ${PROJECT_NAME}
        - name: PATH
          value: ${PATH}
        command: ["nginx", "-g", "daemon off;"]
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: ${SERVICE_NAME}
  labels:
    app: ephemeral-url
spec:
  selector:
    app: ephemeral-url
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  type: ClusterIP
